apiVersion: v1
kind: Service
metadata:
	name: backend
	namespace: malicious-url-detector
spec:
	selector:
		app: backend
	ports:
		- protocol: TCP
			port: 8000
			targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
	name: frontend
	namespace: malicious-url-detector
spec:
	selector:
		app: frontend
	ports:
		- protocol: TCP
			port: 3000
			targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
	name: redis
	namespace: malicious-url-detector
spec:
	selector:
		app: redis
	ports:
		- protocol: TCP
			port: 6379
			targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
	name: postgres
	namespace: malicious-url-detector
spec:
	selector:
		app: postgres
	ports:
		- protocol: TCP
			port: 5432
			targetPort: 5432